### ISSUE TITLE
Baby Steps

### ISSUE THREAD

**Issue by dmcennis** [cosmir/open-mic#12]
We still don't have a firm grasp of what we are trying to build. May I recommend subprojects for this as a first step.

Annotation - human evaluation and ground truth ingestion platform
Ingestion - Uploading audio and database management with metadata maintenance.
Evaluation - API server for evaluating annotations that are computer generated
Execution - Allowing algorithms to access audio itself.

Some or all of these projects can be combined on one machine, but they are distinct sub-projects and require planning for each. Some may be dropped entirely depending on design decisions we haven't made yet (or at least not yet written down...)

**Comment by dmcennis** [comment]
This decision impacts #7 #8 #9 #10 #11

**Comment by dmcennis** [comment]
First Question? Are we using pre-packaged digital library software to manage our data? Will it be Drupal or one of the others?

**Comment by cjacoby** [comment]
+1 subprojects

I think it will be cleaner to manage github issues for the subcomponents
that way.

**Comment by douglaseck** [comment]
Could you outline what some of the other alternatives are? It would be
helpful to have a complete list before deciding on whether or not to use a
pre-packaged solution.

**Comment by dmcennis** [comment]
Drupal (drpal.org) DSpace (dspace.org) and greenstone (greenstone.org) are the 3 digital library packages for managing data I know of. Alternatively, we could forgo interface management and use Elastic search or Solr for managing data content or annotation searching.

**Comment by bmcfee** [comment]
Executive decision: no php.

**Comment by ejhumphrey** [comment]
FWIW, much of the intended infrastructure is sketched out between the ISMIR paper, the slides, and the annotation doc / schema I circulated last week. 

A handful of other thoughts I'll list for clarity:
- Audio will be distributed to participants. We will not be worrying about features, algorithm execution, or any of the `Execution` part.
- After surveying the landscape, I'd argue strongly for Google Cloud Storage for hosting binary data (i.e. buckets), DataStore for records / user data (i.e. hosted NoSQL), and a simple flask server on App Engine (autoscaling web apps) to manage things.
- Subprojects are a great idea, and would like the consensus of conversation here to show up in #11; the projects themselves are at least (a) an audio CMS, (b) a javascript web annotator. We might need to contribute to `mir_eval` re: evaluation.
- The priority here is (1) Ingestion, (2) Annotation, and (3) Evaluation. We will build (1) and (2), and (3) if codalab doesn't cut the mustard.

**Comment by julian-urbano** [comment]
> Executive decision: no php.
EDIT: addendum, no java either. And certainly no matlab.

Assuming no .net either, you're throwing me out of the programming group :bowtie: I hope R is still good around here! I'm getting rusty with tech, I admit.

+1 to @ejhumphrey as well. Much is already outlined in the paper and slides. Big points are being missed!

**Comment by ejhumphrey** [comment]
@julian-urbano sounds like a great opportunity to shake of some of the rust 😉

**Comment by dmcennis** [comment]
Sounds great: Here's an updated set of requirements for the project as my current best guess. Please correct here and at the other sites as we define the first functioning version capabilities.

- Updates to #8 as we'll be rolling our own.
- We'll need Annotation management javascript master as well - rolling into #8 
- We'll need to manage our own database - at least some web front to group CC music ingestion
- We'll need a data page for user stats and the like (Badges?)
- A set of scripts for launching our first evaluation test run
- Task management (Luigi?) for monitoring progress / launching generating results and their evaluation
- place for evaluation description pages
- webpage or other interface for picking which evaluation metrics on which runs of the database

**Comment by ejhumphrey** [comment]
Since most of the outline above has started showing up in other issues, I'm going to shelve this one for now.
