### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by alastair** [cosmir/open-mic#18]
re: https://github.com/omec/bedevere/commit/685a9291d92fd2e394154b31b7346b23cabdeae1#diff-39fadc880c961d928e3a30f64d17805aR1

It had to come up some time...

The AppEngine flexible environment supports python 3.4: https://cloud.google.com/appengine/docs

I worry that with "2.7 + 3.x compatibility" what it'll actually mean is "runs on 2.7 on appengine, and perhaps on 3 if we remember to use `six` and someone complains enough that they can't get it going"
Python 2 goes out of support in 2020 (do we have a wish to keep this project going past then?)

I've been using python 3.5 for all new projects that I've started in the last 6 months and it's been great. I honestly haven't had any trouble with the context shift. Do we have specific reasons (dependencies that will be run on the server) to keep supporting 2.7? If not, I'd recommend we take the plunge and just support 3.4+

**Comment by ejhumphrey** [comment]
+1 (or 3.5?) to python 3 usage. I too made the switch in my own work and think it's just swell, and also encourage anyone who will listen to do the same. I know @cjacoby and @bmcfee are in a similar boat here.

I'm curious to hear the arguments are for explicitly _not_ supporting python 2. For my part, I think backwards compatibility is fine, and it'd be sufficient to keep the requirement that the project [builds in all environments on Travis](https://github.com/omec/bedevere/blob/master/.travis.yml#L12). 

As for App Engine and it's support, I can do a little digging and see what the real state of affairs is there. I don't currently know enough to offer any more perspective on it now.

**Comment by bmcfee** [comment]
> I'm curious to hear the arguments are for explicitly not supporting python 2.

Python 2's crappy unicode support is reason enough for me.

I've spent well more than enough time hacking around encode/decode errors when handling extended character sets for artist/track titles, and I imagine that will be a huge problem in the jamendo data soon enough.

**Comment by alastair** [comment]
> I'm curious to hear the arguments are for explicitly not supporting python 2.

Honestly, for a self-hosted webapp I don't think there are any.

We support 2.6+ in https://github.com/alastair/python-musicbrainzngs, specifically because it's a library used by others (and at the time we last addressed it, the current RHEL release still had 2.6), however my policy is that I now only support it implicitly. If it continues to work, great. However, I'm not going to go out of my way to not use a feature that I need because it's not in the old version

> Python 2's crappy unicode support is reason enough for me.

+1

**Comment by ejhumphrey** [comment]
so, put compactly, maintaining backwards compatibility with python 2.x is more effort than it's worth?

**Comment by alastair** [comment]
I love how you said "backwards compatibility" instead of "forwards compatibility".

Yes.

**Comment by bmcfee** [comment]
> so, put compactly, maintaining backwards compatibility with python 2.x is more effort than it's worth?

It's usually not that much effort, but sure.  I do all development in py3.5 environments, and have tests run in 2.7 and 3.4 envs as well.  (In case it needs saying, jams and mir_eval are both py3-compatible, so we'll have no issues there.)

**Comment by ejhumphrey** [comment]
facing the wrong way and moving backwards is still progress, no? 😉

**Comment by alastair** [comment]
> It's usually not that much effort, but sure.

Agreed. As long as you import the right things from future, most stuff continues to work. I'm thinking about things like unicode, urllib stuff (requests helps here), and `mydict.keys()[2]` not working in 3.x (`keys()` returns a view). If we write stuff that happens to work in 2.7, great, but let's be very clear that our first supported version is 3.4 (I'd love to use 3.5, but it looks like appengine doesn't support it yet)

**Comment by ejhumphrey** [comment]
couple quick thoughts:
- summarizing our sentiments, I'd offer the following proposal: "We're targeting a python3.x project, and supporting python2.x implicitly. If / when our implicit py2.x support becomes enough of a nuisance to whoever has to deal with it, we drop support (on a proposed / seconded)." any objections / concerns? 
- AFAIK, GCP seems to be receptive to their users helping to set priority and roadmap for the product. I can follow-up on my side and see what python3 support looks like to them.

**Comment by ejhumphrey** [comment]
I'd deem this sufficient consensus reached
