### ISSUE TITLE
Roadmap / Planning Document

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/open-mic#5]
this one deserves its own issue: we need to (collaboratively) produce a working document that scopes out what needs to happen and in what time frame.

**Comment by stefan-balke** [comment]
What you have in mind? Will the project's wiki do?

**Comment by ejhumphrey** [comment]
I think we'd start in google docs (handles collaboration better), and then migrate to the wiki once it's stabilized

**Comment by ejhumphrey** [comment]
for posterity, here's a sketch of how the Annotation and Content Management Backend could talk to each other: https://docs.google.com/document/d/1_Ta7I8liVUq29GVbmvHYhv4iXc_ybw72_POA5GPUdNc/edit?usp=sharing

**Comment by dmcennis** [comment]
Love it, but the content on the task list is evolving beautifully and
rapidly, both in content and design. Does someone want to port any
remaining relevant content in task lists and maintain this as the master
repository? If not, any objections to me merging the remainder with
existing task discussions?

**Comment by ejhumphrey** [comment]
sorry, I'm not clear on what you're proposing. what do you mean by "master repository"? and merging what content with / into which discussions?

**Comment by ejhumphrey** [comment]
Here's a version of a roadmap I've sketched out recently in preparation for discussing this project while visiting with some awesome research groups:

![screenshot 2016-09-16 08 35 43](https://cloud.githubusercontent.com/assets/926379/18577274/b980635c-7be8-11e6-849f-21f990429c66.png)

I plan to move it to a proper Google Drawing in the drive folder soon so we can edit / fork it together, but figure we can start discussing it now as-is.

**Comment by ejhumphrey** [comment]
spent some time iterating on the [Content Annotation System design doc](https://drive.google.com/open?id=1_Ta7I8liVUq29GVbmvHYhv4iXc_ybw72_POA5GPUdNc), some of which I've migrated to the main README.

any / all feedback is welcome! I'm particularly interested in issues of clarity, which pieces need elaboration or revision, or if / when any of the ideas proposed aren't great. 

I don't expect for this doc to be 100% finished for our fundamentals, but it's in a good place to discuss with those who care.
