### ISSUE TITLE
Is this currently on hold/shelved?

### ISSUE THREAD

**Issue by JamesOwers** [cosmir/open-mic#51]
Hello,

I'm wondering what the status of this project is. If it has been depreciated, are there any projects that have superseded it?

**Comment by bmcfee** [comment]
Sorry for the radio silence!

The project is not deprecated or shelved -- it is in progress.  Updates are scarce as we're currently finishing up the production of the initial development set, and there is much (internal) validation of data to be done before the release.

**Comment by JamesOwers** [comment]
Great news, thank you for the speedy update.
