### ISSUE TITLE
Authenticated user sessions w/backend

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/open-mic#9]
- [ ] user sign-up -> datastore
- [x] user login
- [x] authenticate `audio/upload`s
- [x] authenticate `annotation/submit`s

**Comment by alastair** [comment]
How do you want to manage authentication? Do it ourselves, or pass off to oauth (facebook,google,github,twitter?)

Can any authenticated user submit audio and annotations or are groups/permissions required?

**Comment by ejhumphrey** [comment]
per [this](https://docs.google.com/document/d/1_Ta7I8liVUq29GVbmvHYhv4iXc_ybw72_POA5GPUdNc/edit#heading=h.c3lh81c442c4), I'm planning to use OAuth via other services. Google makes it [wicked easy](https://developers.google.com/identity/sign-in/web/), so that's probably a fine place to start.

_Can anyone submit audio?_ No, we'll restrict that to at least the dev group, and from there maybe even a few select individuals. This might be easiest by actually not having an `audio/ingest` endpoint, instead having machinery that must be properly credentialed locally.

_Can anyone submit annotations?_ Yes, once logged in. If it comes to it, we can scrub data from bad actors, or lock them out of the system if / when identified.

**Comment by julian-urbano** [comment]
If we plan on implementing the credit system by which annotations give you  points and system runs consume them, we should be able to link several user accounts together as part of an org account or something like that, so they can share credit.

**Comment by ejhumphrey** [comment]
A "credit system" is a good thing to be aware of / have on the roadmap, though I might argue against it for the first iteration. 

Regardless, it'd be great if _someone_ could document a proposal about how such a system would work, what problems it solves, and other such thoughts ... 😉

**Comment by dmcennis** [comment]
Love the credit system idea. It will help keep analysis costs in reach for
PhD students and still keep the door open for those that would rather
donate cash than provide free labor.

**Comment by ejhumphrey** [comment]
in the course of progress elsewhere, there are a few options to consider:
- AppEngine can [enforce login](https://cloud.google.com/appengine/docs/python/config/appref#handlers_element) around specific routes, which is shiny. However, I think this forces everyone to go through google? Not yet clear from the docs.
- Similarly, we can _also_ hide specific routes behind admin credentials, which might help address the "who can upload audio" question. Again, same caveat as above.
- Alternatively, user logins can be punted to the server itself. For this, we can use the Python [Users API](https://cloud.google.com/appengine/docs/python/users/) from Google, which doesn't seem too gnarly ... or something like [Flask-OAuth](https://pythonhosted.org/Flask-OAuth/), which is both more flexible and complicated.

These bullets are ordered in increasing complexity, so it probably makes the most sense to work top-down until we find a solution that works.

**Comment by ejhumphrey** [comment]
0a8ef65 takes care of a big chunk of this, not far off from a PR

**Comment by ejhumphrey** [comment]
this is done as of #48
